-- =============================================================
-- FlowState -- RUN_ALL.sql
-- =============================================================
-- Auto-generated by concatenating every file in migrations/ in
-- order. Every migration in this project is written to be safe
-- to re-run (create table/column/index all use IF NOT EXISTS,
-- every RLS policy is DROP POLICY IF EXISTS + CREATE POLICY, every
-- seed INSERT is guarded with ON CONFLICT or an existence check).
--
-- That means this file is always safe to paste into the Supabase
-- SQL editor and run in full, regardless of which individual
-- migrations have or haven't been applied already -- it brings the
-- database fully in sync with the repo with zero guesswork about
-- migration history. This is the fix for the recurring class of
-- bug where a migration was written but never actually run against
-- the live database (missing columns, missing RLS policies) and
-- the app failed silently or with a confusing error.
--
-- Regenerate this file any time a new migration is added:
--   cd supabase && for f in migrations/*.sql; do (echo; echo "-- ---- $f ----"; cat "$f") >> RUN_ALL.sql
-- (or just ask Claude to regenerate it)
--
-- NOTE: supabase/schema.sql is NOT included here -- it is the
-- original pre-migrations bootstrap for a generic workflow system
-- that migration 019_drop_legacy_workflows.sql deliberately tears
-- down. It is historical only; do not run it.
-- =============================================================

-- =============================================================
-- ---- migrations/004_day_planning.sql ----
-- =============================================================
-- Day planning tables: daily_tasks, daily_intentions, routine_completions
-- These replace Notion as the primary store for the day planner

create table if not exists daily_tasks (
  id              uuid primary key default gen_random_uuid(),
  title           text not null,
  due_date        date,
  status          text not null default 'Not started',
  urgency         text,
  importance      text,
  time_commitment text,
  task_type       text,
  is_frog         boolean not null default false,
  why_note        text,
  notion_id       text unique,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table if not exists daily_intentions (
  id              uuid primary key default gen_random_uuid(),
  intention_date  date not null unique,
  intention_text  text not null default '',
  locked          boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table if not exists routine_completions (
  id             uuid primary key default gen_random_uuid(),
  routine_date   date not null unique,
  completed_at   timestamptz not null default now()
);

create index if not exists daily_tasks_due_date_idx on daily_tasks(due_date);
create index if not exists daily_tasks_status_idx on daily_tasks(status);

create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists daily_tasks_updated_at on daily_tasks;
create trigger daily_tasks_updated_at
  before update on daily_tasks for each row execute function set_updated_at();

drop trigger if exists daily_intentions_updated_at on daily_intentions;
create trigger daily_intentions_updated_at
  before update on daily_intentions for each row execute function set_updated_at();

-- =============================================================
-- ---- migrations/005_tasks.sql ----
-- =============================================================
-- 005_tasks.sql
-- Central tasks table: authoritative store for all tasks (synced from Notion, created in-app)
-- Replaces the split daily_tasks + Notion API approach.
--
-- Guard: an older, incompatible "tasks" table can already exist on the live
-- database from the original schema.sql (the legacy generic-workflow system,
-- with stage_id/instructions columns and no "archived" column). If it's still
-- there, "create table if not exists" below is a no-op against it and the
-- indexes further down fail with "column archived does not exist". That
-- legacy table is unconditionally dropped later anyway (019_drop_legacy_workflows.sql,
-- superseded by master_tasks from 010_master_tasks.sql), so it's always safe
-- to drop it here too rather than let this migration fail on old data.
do $$
begin
  if to_regclass('public.tasks') is not null
     and not exists (
       select 1 from information_schema.columns
       where table_name = 'tasks' and column_name = 'archived'
     )
  then
    drop table tasks cascade;
  end if;
end $$;

create table if not exists tasks (
  id               uuid        primary key default gen_random_uuid(),
  notion_id        text        unique,                          -- deduplication key for Notion sync
  title            text        not null,
  status           text        not null default 'Not started', -- 'Not started' | 'In progress' | 'Done'
  due_date         date,
  task_type        text,                                        -- 'Flow' | 'Recurring' | 'Quick Task' | 'Admin' | 'Personal'
  urgency          text,                                        -- 'Urgent' | 'Habit' | 'Non Urgent'
  importance       text,                                        -- 'Moved the Needle' | 'Non Important' | 'Important'
  time_commitment  text,                                        -- '60 + mins' | '30 - 60 mins' | '15 - 30 mins' | '< 15mins'
  is_frog          boolean     not null default false,          -- top priority task of the day
  priority         text,                                        -- 'Low' | 'Medium' | 'High'
  why_note         text,                                        -- personal reason / motivation note
  notion_url       text,                                        -- link back to Notion page
  archived         boolean     not null default false,          -- soft delete
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- Performance indexes
create index if not exists tasks_due_date_idx
  on tasks(due_date)
  where archived = false;

create index if not exists tasks_status_idx
  on tasks(status)
  where archived = false and status != 'Done';

create index if not exists tasks_frog_idx
  on tasks(due_date, is_frog)
  where archived = false and is_frog = true;

create index if not exists tasks_type_idx
  on tasks(task_type, due_date)
  where archived = false;

-- Auto-update updated_at on every row change
create or replace function tasks_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tasks_updated_at on tasks;
create trigger tasks_updated_at
  before update on tasks
  for each row execute procedure tasks_set_updated_at();

-- Enable RLS (personal app -- allow all for anon key)
alter table tasks enable row level security;

drop policy if exists "allow_all_tasks" on tasks;
create policy "allow_all_tasks" on tasks
  for all using (true) with check (true);

-- =============================================================
-- ---- migrations/006_habits.sql ----
-- =============================================================
-- ============================================================
-- 006_habits.sql  —  Habit tracker
-- ============================================================

-- habits: one row per habit definition
create table if not exists habits (
  id              uuid        primary key default gen_random_uuid(),
  title           text        not null,
  description     text,
  -- schedule_type: 'daily' | 'weekdays' | 'weekends' | 'custom'
  schedule_type   text        not null default 'daily',
  -- schedule_days: array of weekday ints (0=Sun … 6=Sat) used when type='custom'
  schedule_days   integer[]   not null default '{}',
  -- optional target time 'HH:MM' — used for accountability warnings
  schedule_time   text,
  color           text        not null default '#00d4ff',
  emoji           text        not null default '✓',
  sort_order      integer     not null default 0,
  active          boolean     not null default true,
  created_at      timestamptz not null default now()
);

-- habit_completions: one row per habit per calendar day it was checked off
create table if not exists habit_completions (
  id              uuid        primary key default gen_random_uuid(),
  habit_id        uuid        not null references habits(id) on delete cascade,
  completed_date  date        not null,
  completed_at    timestamptz not null default now(),
  -- prevent duplicate completions for the same day
  unique(habit_id, completed_date)
);

-- Indexes
create index if not exists habit_completions_habit_id_idx     on habit_completions(habit_id);
create index if not exists habit_completions_date_idx         on habit_completions(completed_date);

-- Auto-updated_at is not needed for these simple tables

-- ---- RLS (open policy for personal single-user app) ----
alter table habits            enable row level security;
alter table habit_completions enable row level security;

drop policy if exists allow_all_habits            on habits;
drop policy if exists allow_all_habit_completions on habit_completions;

create policy allow_all_habits            on habits            for all using (true) with check (true);
create policy allow_all_habit_completions on habit_completions for all using (true) with check (true);

-- ---- Seed: default habits ----
insert into habits (title, description, schedule_type, schedule_days, schedule_time, color, emoji, sort_order) values
  ('Morning routine',        'Complete the full morning routine',                'daily',    '{}',        '08:00', '#00d4ff', '🌅', 0),
  ('Deep work session',      'At least one 90-min focus block',                  'weekdays', '{}',        '10:00', '#00ff88', '🎯', 1),
  ('Exercise',               'Move your body — gym, run, or walk',               'daily',    '{}',        '07:00', '#ffb800', '💪', 2),
  ('Read / listen 10 pages', 'Minimum 10 pages of a book or Welsh learning',     'daily',    '{}',        '21:30', '#8b5cf6', '📚', 3),
  ('Talk / Read Welsh',      'Welsh practice — Duolingo, reading or speaking',   'daily',    '{}',        '21:00', '#ff4466', '🏴󠁧󠁢󠁷󠁬󠁳󠁿', 4),
  ('No phone after 9pm',     'Phone in another room, no scrolling',              'daily',    '{}',        '21:00', '#4a4a6a', '📵', 5),
  ('Magnesium',              'Take magnesium supplement before bed',             'daily',    '{}',        '21:30', '#00d4ff', '💊', 6),
  ('Collagen 10g',           '10g collagen in water before bed',                 'daily',    '{}',        '21:30', '#ffb800', '🥛', 7)
on conflict do nothing;

-- =============================================================
-- ---- migrations/007_vault.sql ----
-- =============================================================
-- ============================================================
-- 007_vault.sql  —  Knowledge base (Notion vault items)
-- task/vault = 'vault' rows from the master DB
-- ============================================================

create table if not exists vault_items (
  id              uuid        primary key default gen_random_uuid(),
  notion_id       text        unique,
  title           text        not null,
  category        text,        -- Book | Article | Tool / Software | Business Idea | Reference | Movie | Academic | Audiobook / Podcast | Video | Spreadsheet | Buy
  author_source   text,
  link            text,
  key_takeaway    text,
  notes           text,
  platform        text,        -- Wealthmack | Website | Shopify | Etsy | YouTube | Twitter
  tag             text,        -- SEO | Design | Film | Edit | Script
  status          text        not null default 'Not started',
  notion_url      text,
  archived        boolean     not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists vault_items_category_idx  on vault_items(category);
create index if not exists vault_items_tag_idx       on vault_items(tag);
create index if not exists vault_items_archived_idx  on vault_items(archived);

alter table vault_items enable row level security;
drop policy if exists allow_all_vault on vault_items;
create policy allow_all_vault on vault_items for all using (true) with check (true);

create or replace function update_vault_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;
drop trigger if exists trg_vault_updated_at on vault_items;
create trigger trg_vault_updated_at
  before update on vault_items
  for each row execute function update_vault_updated_at();

-- =============================================================
-- ---- migrations/008_content.sql ----
-- =============================================================
-- ============================================================
-- 008_content.sql  —  YouTube content pipeline
-- Items from master DB that have a YT Pipeline Stage set
-- ============================================================

create table if not exists content_items (
  id              uuid        primary key default gen_random_uuid(),
  notion_id       text        unique,
  title           text        not null,
  pipeline_stage  text,        -- 💡 Idea | 📚 Research | 📝 Scripting | 🎙️ Voiceover | 🎨 Assets | ✂️ Editing | 🖼️ Thumbnail & SEO | ☁️ Ready to Upload | 📣 Live
  format          text,        -- Both | Short | Long form
  yt_length       text,        -- Long form | Short form (multi-select stored as comma-sep)
  tag             text,        -- SEO | Design | Film | Edit | Script
  due_date        date,
  status          text        not null default 'Not started',
  link            text,
  notes           text,
  notion_url      text,
  archived        boolean     not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists content_pipeline_stage_idx on content_items(pipeline_stage);
create index if not exists content_due_date_idx       on content_items(due_date);
create index if not exists content_archived_idx       on content_items(archived);

alter table content_items enable row level security;
drop policy if exists allow_all_content on content_items;
create policy allow_all_content on content_items for all using (true) with check (true);

create or replace function update_content_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;
drop trigger if exists trg_content_updated_at on content_items;
create trigger trg_content_updated_at
  before update on content_items
  for each row execute function update_content_updated_at();

-- =============================================================
-- ---- migrations/009_projects.sql ----
-- =============================================================
-- ============================================================
-- 009_projects.sql  —  Projects (separate Notion DB)
-- DB ID: 352ed686-b47d-8035-8c12-000bc64736c4
-- ============================================================

create table if not exists projects (
  id              uuid        primary key default gen_random_uuid(),
  notion_id       text        unique,
  title           text        not null,
  status          text        not null default 'Not started', -- Not started | In progress | Paused | Done
  priority        text,        -- Low | Medium | High
  deadline        date,
  goal            text,        -- "Why does this project exist"
  next_action     text,        -- "Single Next Action"
  notes           text,
  notion_url      text,
  archived        boolean     not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists projects_status_idx   on projects(status);
create index if not exists projects_deadline_idx on projects(deadline);
create index if not exists projects_archived_idx on projects(archived);

alter table projects enable row level security;
drop policy if exists allow_all_projects on projects;
create policy allow_all_projects on projects for all using (true) with check (true);

create or replace function update_projects_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;
drop trigger if exists trg_projects_updated_at on projects;
create trigger trg_projects_updated_at
  before update on projects
  for each row execute function update_projects_updated_at();

-- =============================================================
-- ---- migrations/010_master_tasks.sql ----
-- =============================================================
-- 010_master_tasks.sql
-- Personal tasks table — renamed from 'tasks' to avoid collision with YouTube workflow tasks table.
-- The YouTube workflow 'tasks' table (schema.sql) has stage_id/instructions/etc.
-- This table holds personal/Notion-imported tasks.

create table if not exists master_tasks (
  id               uuid        primary key default gen_random_uuid(),
  notion_id        text        unique,
  title            text        not null,
  status           text        not null default 'Not started',
  due_date         date,
  task_type        text,
  urgency          text,
  importance       text,
  time_commitment  text,
  is_frog          boolean     not null default false,
  priority         text,
  why_note         text,
  notion_url       text,
  archived         boolean     not null default false,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists master_tasks_due_date_idx
  on master_tasks(due_date)
  where archived = false;

create index if not exists master_tasks_status_idx
  on master_tasks(status)
  where archived = false;

-- RLS: allow all operations with anon key
alter table master_tasks enable row level security;

drop policy if exists allow_all_master_tasks on master_tasks;
create policy allow_all_master_tasks on master_tasks for all using (true) with check (true);

-- =============================================================
-- ---- migrations/011_personal_goals.sql ----
-- =============================================================
-- personal_items: lifestyle goals, habits, ideas from Notion Personal database
create table if not exists personal_items (
  id uuid primary key default gen_random_uuid(),
  notion_id text unique,
  name text not null,
  priority text not null default 'Medium', -- High | Medium | Low
  notes text,
  notion_url text,
  archived boolean not null default false,
  created_at timestamptz not null default now()
);
alter table personal_items enable row level security;
drop policy if exists allow_all_personal_items on personal_items;
create policy allow_all_personal_items on personal_items for all using (true) with check (true);

-- goals: hierarchical goals from Notion Goals database
create table if not exists goals (
  id uuid primary key default gen_random_uuid(),
  notion_id text unique,
  name text not null,
  priority text, -- P0 | P1 | P2
  status text,   -- Green | Yellow | Red
  is_top_level boolean not null default false,
  notion_url text,
  archived boolean not null default false,
  created_at timestamptz not null default now()
);
alter table goals enable row level security;
drop policy if exists allow_all_goals on goals;
create policy allow_all_goals on goals for all using (true) with check (true);

-- =============================================================
-- ---- migrations/012_localstorage_sync.sql ----
-- =============================================================
-- 012_localstorage_sync.sql
-- Migrate localStorage-only data to Supabase for cross-device sync

-- ── Reminders ────────────────────────────────────────────────────────────────
create table if not exists reminders (
  id          text        primary key,
  title       text        not null,
  emoji       text        not null default '',
  color       text        not null default '#00ff88',
  start_date  text        not null,
  recurrence  jsonb       not null default '{"type":"daily"}',
  time_label  text        not null default ''
);

-- ── Habit blocks (calendar recurring habit display) ───────────────────────────
create table if not exists habit_blocks (
  id          text        primary key,
  title       text        not null,
  emoji       text        not null default '',
  color       text        not null default '#00d4ff',
  days        integer[]   not null default '{}',
  time_label  text        not null default ''
);

-- ── Generic checklist state (YouTube, Etsy, etc.) ────────────────────────────
-- key = 'yt_creation' | 'yt_shorts' | 'etsy_checklists'
-- state = JSON array of checked item IDs (YouTube) or {id: bool} object (Etsy)
create table if not exists checklist_state (
  key         text        primary key,
  state       jsonb       not null default '[]',
  updated_at  timestamptz not null default now()
);

-- ── Welsh quiz progress (single row) ─────────────────────────────────────────
create table if not exists welsh_progress (
  id          integer     primary key default 1,
  streak      integer     not null default 0,
  best        integer     not null default 0,
  last_date   text        not null default ''
);
-- Ensure row exists
insert into welsh_progress (id, streak, best, last_date)
values (1, 0, 0, '')
on conflict (id) do nothing;

-- ── Welsh custom vocabulary ───────────────────────────────────────────────────
create table if not exists welsh_custom_words (
  id          text        primary key,
  en          text        not null,
  cy          text        not null,
  created_at  timestamptz not null default now()
);

-- =============================================================
-- ---- migrations/012_workspace_links.sql ----
-- =============================================================
create table if not exists workspace_links (
  id uuid primary key default gen_random_uuid(),
  notion_id text unique,
  name text not null,
  url text,
  select_type text,   -- 'Watch' | 'Read' | null
  priority text,      -- 'Important' | 'Medium' | 'Long Term' | null
  checked boolean not null default false,
  created_at timestamptz not null default now()
);
alter table workspace_links enable row level security;
drop policy if exists allow_all_workspace_links on workspace_links;
create policy allow_all_workspace_links on workspace_links for all using (true) with check (true);

-- =============================================================
-- ---- migrations/013_etsy_team_space.sql ----
-- =============================================================
-- Migration: 013_etsy_team_space
-- TopNotchThreadz Team Space tables for Supabase import

-- ── Etsy Todos ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS etsy_todos (
  id              BIGSERIAL PRIMARY KEY,
  name            TEXT        NOT NULL,
  stage           TEXT        CHECK (stage IN ('Not Started','Started','Ongoing','Completed')),
  priority        TEXT        CHECK (priority IN ('High','Medium','Low')),
  notes           TEXT,
  target_date_start TIMESTAMPTZ,
  target_date_end   TIMESTAMPTZ,
  notion_url      TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── Etsy Links ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS etsy_links (
  id         BIGSERIAL PRIMARY KEY,
  name       TEXT        NOT NULL,
  url        TEXT,
  tags       TEXT,
  created    TIMESTAMPTZ,
  notion_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Etsy Batch Workflow ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS etsy_batch_workflow (
  id                   BIGSERIAL PRIMARY KEY,
  notion_id            INTEGER,
  idea_theme           TEXT        NOT NULL,
  niche                TEXT,
  batch_priority       TEXT        CHECK (batch_priority IN ('Low','Medium','High')),
  batch_stage          TEXT        CHECK (batch_stage IN (
                          'Research + Ideas','Designing','Uploading','Monitoring','Archive')),
  method               TEXT,
  legal_check          BOOLEAN     DEFAULT FALSE,
  niche_research_stage TEXT,
  seed_keyword         TEXT,
  notes                TEXT,
  ideas_url            TEXT,
  design_url           TEXT,
  ai_design_link       TEXT,
  details_url          TEXT,
  date_start           TIMESTAMPTZ,
  date_end             TIMESTAMPTZ,
  notion_url           TEXT,
  created_at           TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_etsy_todos_stage    ON etsy_todos (stage);
CREATE INDEX IF NOT EXISTS idx_etsy_todos_priority ON etsy_todos (priority);
CREATE INDEX IF NOT EXISTS idx_etsy_batch_stage    ON etsy_batch_workflow (batch_stage);
CREATE INDEX IF NOT EXISTS idx_etsy_batch_priority ON etsy_batch_workflow (batch_priority);
CREATE INDEX IF NOT EXISTS idx_etsy_batch_niche    ON etsy_batch_workflow (niche);

-- =============================================================
-- ---- migrations/014_etsy_notes_pipeline.sql ----
-- =============================================================
-- Migration: 014_etsy_notes_pipeline
-- Etsy Notes and Software Pipeline tables

CREATE TABLE IF NOT EXISTS etsy_notes (
  id         BIGSERIAL PRIMARY KEY,
  name       TEXT        NOT NULL,
  priority   TEXT        CHECK (priority IN ('High','Medium','Low')),
  notes      TEXT,
  file_url   TEXT,
  notion_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS etsy_software_pipeline (
  id         BIGSERIAL PRIMARY KEY,
  name       TEXT        NOT NULL,
  status     TEXT,
  priority   TEXT        CHECK (priority IN ('High','Medium','Low')),
  notes      TEXT,
  file_url   TEXT,
  notion_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_etsy_notes_priority    ON etsy_notes (priority);
CREATE INDEX IF NOT EXISTS idx_etsy_pipeline_status   ON etsy_software_pipeline (status);
CREATE INDEX IF NOT EXISTS idx_etsy_pipeline_priority ON etsy_software_pipeline (priority);

-- =============================================================
-- ---- migrations/015_priority_lists.sql ----
-- =============================================================
-- 015_priority_lists.sql
-- Stores user-defined drag-sorted priority order for any item list.
-- key identifies the list (e.g. 'tasks_priority', 'vault_priority', 'etsy_todos_priority', 'youtube_priority')
-- ordered_ids is a JSON array of item IDs in priority rank order (1st = highest)

create table if not exists priority_lists (
  key         text        primary key,
  ordered_ids jsonb       not null default '[]'::jsonb,
  updated_at  timestamptz not null default now()
);

-- RLS: allow all operations with anon key
alter table priority_lists enable row level security;
drop policy if exists allow_all_priority_lists on priority_lists;
create policy allow_all_priority_lists on priority_lists for all using (true) with check (true);

-- =============================================================
-- ---- migrations/016_from_vault.sql ----
-- =============================================================
-- 016_from_vault.sql
-- Tracks tasks that were converted from vault items, so the task page
-- can highlight them as needing urgency / type / priority assignment.

alter table master_tasks add column if not exists from_vault boolean not null default false;

-- =============================================================
-- ---- migrations/017_content_growth_fields.sql ----
-- =============================================================
-- ============================================================
-- 017_content_growth_fields.sql  —  Growth-lever fields for content_items
-- Additive only, flowstate-local (not sourced from Notion sync — the
-- Notion upsert in app/api/sync/notion/route.ts only ever writes the
-- columns it explicitly lists, so these are safe to add without
-- touching the sync).
--
-- video_type    — which of the four funnel roles this video plays
-- unique_angle  — the "alpha" check: what this video has that a
--                 generic AI answer or the top existing videos don't
-- revenue_note  — manual revenue attribution logged at Post-Published,
--                 since views alone don't tell you what actually paid
-- ============================================================

alter table content_items add column if not exists video_type text;
-- How-To | Listicle | Case Study | Explainer

alter table content_items add column if not exists unique_angle text;
alter table content_items add column if not exists revenue_note text;

create index if not exists content_video_type_idx on content_items(video_type);

-- =============================================================
-- ---- migrations/017_site_ideas.sql ----
-- =============================================================
-- 017_site_ideas.sql
-- Backlog of website/app ideas shown on the home page, with add/edit/remove
-- support. Seeded with the ideas already discussed so nothing is lost.

create table if not exists site_ideas (
  id         uuid primary key default gen_random_uuid(),
  title      text not null,
  tag        text not null default 'Other',
  summary    text not null default '',
  next_step  text not null default '',
  sort_order int  not null default 0,
  created_at timestamptz not null default now()
);

alter table site_ideas enable row level security;
drop policy if exists allow_all_site_ideas on site_ideas;
create policy allow_all_site_ideas on site_ideas for all using (true) with check (true);

-- Guard the seed so re-running this migration doesn't duplicate rows
-- (site_ideas has no natural unique key to conflict on).
insert into site_ideas (title, tag, summary, next_step, sort_order)
select * from (values
('Word of Welsh', 'Website',
 'A daily/weekly Welsh word site -- one word, meaning, pronunciation and an example sentence, maybe a streak to keep people coming back.',
 'This one lives or dies on accuracy. Get Sioned to sign off on word choice, translation and pronunciation before any content goes live -- she is the actual bottleneck here, not the build. Once she is on board the site itself is simple: word-of-the-day, an archive, a shareable card.',
 0),
('5-a-side app & Football Goffy', 'App',
 'Two related football ideas -- a 5-a-side game organiser (fill a game, manage regulars, split costs) and "Football Goffy" (concept still needs fleshing out).',
 'Pick one to scope first. The 5-a-side organiser has proven demand -- Playo, TeamUp and Spond already exist, so study what they get wrong before building rather than starting from scratch. Goffy needs a one-paragraph concept written down before it can be scoped at all.',
 1),
('Old Money / Luxury Spending', 'Website',
 'Content site in the "old money" / quiet luxury niche -- brand guides, style rules, where old money actually spends.',
 'The angle is trending on TikTok and Pinterest right now, so demand is not the question -- monetisation is. Affiliate links to the brands featured is the obvious model, but a paid style guide or membership could work too. Decide that before writing a word.',
 2),
('Movie Site to Beat Rotten Tomatoes', 'Website',
 'A trustworthy alternative to Rotten Tomatoes, positioned against the perceived studio/critic influence on its scores.',
 '"Better than RT" is not a strategy on its own. Nail the actual mechanic that makes it harder to game -- verified-viewer-only scoring, transparent methodology, no paid placements -- before touching a line of code.',
 3),
('Punter''s Revenge & Gambling Theories', 'App',
 'A betting theory and strategy tracking app.',
 'Decide early whether this is pure education and bet-tracking (low regulatory burden) or actually facilitates betting (triggers UK Gambling Commission licensing -- expensive and slow). That single decision shapes the entire build, so settle it before anything else.',
 4),
('Claude Options & Financial Psychology', 'Website',
 'An options-trading education site, using Claude to explain trades and the psychology behind them.',
 'Decide whether this is content (articles/courses) or a tool (AI-assisted trade and psychology analysis) -- the brief specifically calls out layout, so once the content-vs-tool question is answered, start there.',
 5),
('Capitals & Flags Test Site', 'Website',
 'A quiz site testing knowledge of world capitals and flags -- classic trivia format, likely with difficulty levels, streaks or a speedrun mode.',
 'This is the most straightforward build on the list -- no dependency on anyone else and the data (countries, capitals, flag images) is freely available. The differentiator is the game modes, not the content, so sketch out 2-3 quiz formats (multiple choice, speed round, hard mode with no hints) before building rather than shipping a single generic quiz.',
 6)
) as seed(title, tag, summary, next_step, sort_order)
where not exists (select 1 from site_ideas);

-- =============================================================
-- ---- migrations/018_content_focus.sql ----
-- =============================================================
-- ============================================================
-- 018_content_focus.sql — YouTube-Pipeline-driven Focus Session
-- Additive only, flowstate-local (not sourced from Notion sync — the
-- Notion upsert in app/api/sync/notion/route.ts only ever writes the
-- columns it explicitly lists, so these are safe to add without
-- touching the sync).
--
-- is_active_focus        — up to 2 content_items pinned as the Home page's
--                           "active focus" videos/shorts (any pipeline stage).
--                           Enforced to max 2 in the app layer, not the DB.
-- content_step_completions — per-video checklist state for the SOP steps
--                           tied to the item's current pipeline_stage (see
--                           lib/sops.ts STAGE_TO_SOP). Ticking every step for
--                           the current stage is what the new focus session
--                           uses to trigger the pipeline_stage advance.
-- ============================================================

alter table content_items add column if not exists is_active_focus boolean not null default false;

create index if not exists content_items_active_focus_idx on content_items(is_active_focus) where is_active_focus = true;

create table if not exists content_step_completions (
  id                uuid        primary key default gen_random_uuid(),
  content_item_id   uuid        not null references content_items(id) on delete cascade,
  sop_id            text        not null,   -- matches SOP.id in lib/sops.ts, e.g. '02'
  step_index        int         not null,   -- index into that SOP's steps[] array
  completed_at      timestamptz not null default now(),
  unique (content_item_id, sop_id, step_index)
);

create index if not exists content_step_completions_item_idx on content_step_completions(content_item_id);

alter table content_step_completions enable row level security;
drop policy if exists allow_all_content_step_completions on content_step_completions;
create policy allow_all_content_step_completions on content_step_completions for all using (true) with check (true);

-- =============================================================
-- ---- migrations/019_drop_legacy_workflows.sql ----
-- =============================================================
-- =============================================================
-- FlowState — Drop legacy generic workflow system
-- The /workflows, /workflow/[id], /workflow/[id]/focus routes and all
-- app code referencing these tables have been removed. Content that was
-- worth keeping (YouTube Longform + Shorts SOPs) has been folded into
-- lib/sops.ts, which drives the Content Pipeline instead.
--
-- RUN IN SUPABASE SQL EDITOR — safe to re-run
-- =============================================================

drop table if exists task_completions cascade;
drop table if exists workflow_sessions cascade;
drop table if exists tasks cascade;
drop table if exists stages cascade;
drop table if exists workflow_types cascade;

-- =============================================================
-- ---- migrations/020_daily_plan_and_stage_notes.sql ----
-- =============================================================
-- =============================================================
-- FlowState — Daily weighted workflow plan + Pipeline AI-assist
--
-- 1. daily_plans        — the generated/edited plan for a given date,
--                          one row per scheduled block (one section's
--                          top-priority item + a time allocation).
-- 2. daily_plan_settings — single-row config: total working minutes/day
--                          and the % split across the 5 sections.
-- 3. content_stage_notes — AI-assisted (or hand-written) notes per
--                          content_item per SOP stage, so each stage
--                          keeps its own output as a video advances.
-- 4. x_ideas             — lightweight content-idea backlog for X, so
--                          X has something to prioritise like the other
--                          sections (it previously had no persisted list).
--
-- RUN IN SUPABASE SQL EDITOR — safe to re-run
-- =============================================================

create table if not exists daily_plans (
  id          uuid primary key default gen_random_uuid(),
  plan_date   date not null,
  section     text not null,              -- 'youtube' | 'etsy' | 'tasks' | 'x' | 'vault'
  source_id   text,                       -- id of the underlying item, nullable for freeform blocks
  title       text not null,
  minutes     int  not null default 30,
  order_index int  not null default 0,
  status      text not null default 'planned',  -- planned | done | skipped | rescheduled
  created_at  timestamptz not null default now()
);

create index if not exists daily_plans_date_idx on daily_plans (plan_date);

alter table daily_plans enable row level security;
drop policy if exists allow_all_daily_plans on daily_plans;
create policy allow_all_daily_plans on daily_plans for all using (true) with check (true);


create table if not exists daily_plan_settings (
  id           int primary key default 1,
  total_minutes int not null default 360,
  pct_youtube  int not null default 50,
  pct_etsy     int not null default 20,
  pct_tasks    int not null default 15,
  pct_x        int not null default 10,
  pct_vault    int not null default 5,
  updated_at   timestamptz not null default now(),
  constraint daily_plan_settings_singleton check (id = 1)
);

insert into daily_plan_settings (id) values (1) on conflict (id) do nothing;

alter table daily_plan_settings enable row level security;
drop policy if exists allow_all_daily_plan_settings on daily_plan_settings;
create policy allow_all_daily_plan_settings on daily_plan_settings for all using (true) with check (true);


create table if not exists content_stage_notes (
  id              uuid primary key default gen_random_uuid(),
  content_item_id uuid not null references content_items(id) on delete cascade,
  sop_id          text not null,
  output          text,
  updated_at      timestamptz not null default now(),
  unique (content_item_id, sop_id)
);

alter table content_stage_notes enable row level security;
drop policy if exists allow_all_content_stage_notes on content_stage_notes;
create policy allow_all_content_stage_notes on content_stage_notes for all using (true) with check (true);


create table if not exists x_ideas (
  id         uuid primary key default gen_random_uuid(),
  text       text not null,
  status     text not null default 'todo',   -- todo | done
  archived   boolean not null default false,
  created_at timestamptz not null default now()
);

alter table x_ideas enable row level security;
drop policy if exists allow_all_x_ideas on x_ideas;
create policy allow_all_x_ideas on x_ideas for all using (true) with check (true);

-- =============================================================
-- ---- migrations/021_daily_plan_into_tasks.sql ----
-- =============================================================
-- =============================================================
-- FlowState — Fold the weighted daily plan into master_tasks
--
-- Tom wants the Calendar (not a separate Evening-page-only view) to be
-- the single place everything lives, so it inherits the existing
-- drag-to-reschedule, "Organise" (overdue), and "Organise Week" (type
-- rebalancing) behaviour for free. The weighted-plan generator now
-- writes ordinary master_tasks rows instead of a separate daily_plans
-- table — so this migration:
--   1. Adds source_section/source_id to master_tasks so generated rows
--      can be traced back to the pipeline item they came from (and so
--      regenerating doesn't create duplicates).
--   2. Drops the now-unused daily_plans table from 020.
--   3. Leaves daily_plan_settings (the weighting %), content_stage_notes,
--      and x_ideas in place — those are still used.
--
-- RUN IN SUPABASE SQL EDITOR — safe to re-run
-- =============================================================

alter table master_tasks add column if not exists source_section text;
alter table master_tasks add column if not exists source_id text;

create index if not exists master_tasks_source_id_idx on master_tasks (source_id) where source_id is not null;

drop table if exists daily_plans cascade;

-- =============================================================
-- ---- migrations/022_morning_routine.sql ----
-- =============================================================
-- =============================================================
-- FlowState — Move the morning routine checklist into the database
--
-- Previously the item list lived in lib/morningRoutine.ts (hardcoded) and
-- daily completion state lived in localStorage — only an all-or-nothing
-- "did you finish the whole routine" row made it to Supabase
-- (routine_completions, for the streak counter). That meant no way to see
-- which individual items get done vs skipped over time, and no way to add
-- an item without a code change.
--
-- This migration:
--   1. Creates morning_routine_items — the checklist itself, editable at
--      runtime from the app (add/reorder/retire items).
--   2. Creates morning_routine_completions — one row per item per day it
--      was completed, so per-item completion rates can actually be tracked.
--   3. Seeds it with the routine as it existed in code (including the new
--      Welsh/Duolingo item), preserving the same ids so nothing resets.
--
-- routine_completions (the all-done streak table) is untouched — it still
-- works exactly as before, just alongside the new per-item data.
--
-- RUN IN SUPABASE SQL EDITOR — safe to re-run
-- =============================================================

create table if not exists morning_routine_items (
  id text primary key,
  title text not null,
  minutes integer not null default 5,
  note text,
  category text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists morning_routine_completions (
  id uuid primary key default gen_random_uuid(),
  item_id text not null references morning_routine_items(id) on delete cascade,
  completed_date date not null,
  completed_at timestamptz not null default now(),
  unique (item_id, completed_date)
);

create index if not exists morning_routine_completions_date_idx on morning_routine_completions (completed_date);
create index if not exists morning_routine_completions_item_idx on morning_routine_completions (item_id);

alter table morning_routine_items enable row level security;
drop policy if exists allow_all_morning_routine_items on morning_routine_items;
create policy allow_all_morning_routine_items on morning_routine_items for all using (true) with check (true);

alter table morning_routine_completions enable row level security;
drop policy if exists allow_all_morning_routine_completions on morning_routine_completions;
create policy allow_all_morning_routine_completions on morning_routine_completions for all using (true) with check (true);

insert into morning_routine_items (id, title, minutes, note, category, sort_order) values
  ('mr-pushpull',  '5 push-ups / 5 pull-ups',                       5,  'Before breakfast', 'Movement', 0),
  ('mr-weight',    'Weigh yourself + log in spreadsheet',            2,  null, 'Health', 1),
  ('mr-waist',     'Measure waist (if down 2kg since last measure)', 2,  '1 inch lost = fat loss confirmed', 'Health', 2),
  ('mr-floor',     '1 min floor sit, 90/90 switches, child pose',    5,  null, 'Movement', 3),
  ('mr-bounce',    '20 bounces + hold squat 2 minutes',              4,  'Deep squat, heels flat if possible — builds ankle & hip mobility', 'Movement', 4),
  ('mr-ankle',     'Ankle mobility — circles, leans, alphabet',      3,  '10 circles each way, 10 wall leans each foot, trace A-Z with each foot', 'Movement', 5),
  ('mr-breakfast', 'Breakfast: yoghurt + maple syrup',               10, null, 'Fuel', 6),
  ('mr-coffee',    'Coffee + cane sugar + collagen + molasses',      5,  null, 'Fuel', 7),
  ('mr-eggs',      'Eggs on sourdough + mushrooms (weights day)',    15, 'Only on hard weights days', 'Fuel', 8),
  ('mr-read',      'Read 2 pages',                                   5,  null, 'Mind', 9),
  ('mr-welsh',     'Duolingo lesson in Welsh',                       5,  'Minimum 1 lesson', 'Mind', 10),
  ('mr-visualise', 'Process visualisation',                          5,  'Close your eyes. Walk through your day step by step — not the outcome, the PROCESS. See yourself sitting down to work, what your hands are doing, how focused you feel, how you handle the first obstacle. Finish by writing 1 specific action you will take before lunch.', 'Mind', 11)
on conflict (id) do nothing;

-- =============================================================
-- ---- migrations/022_video_links_and_stats.sql ----
-- =============================================================
-- ============================================================
-- 022_video_links_and_stats.sql — Per-video links for the pipeline
--
-- script_url   — where the actual script lives (Google Doc / Drive file)
-- drive_url    — the video's asset folder in Google Drive
-- youtube_url  — the published video, once live; the app extracts the
--                video id from this to pull public stats (views/likes/
--                comments) from the YouTube Data API in one place.
--
-- Additive only, flowstate-local (the Notion sync only writes columns it
-- explicitly lists, so these are safe to add without touching it).
--
-- RUN IN SUPABASE SQL EDITOR — safe to re-run
-- ============================================================

alter table content_items add column if not exists script_url text;
alter table content_items add column if not exists drive_url text;
alter table content_items add column if not exists youtube_url text;

-- =============================================================
-- ---- migrations/023_localstorage_to_db.sql ----
-- =============================================================
-- =============================================================
-- FlowState — migrate the remaining localStorage-only features to Supabase
--
-- These features had zero database backing at all (unlike most of the app,
-- which already uses localStorage purely as an instant-load cache in front
-- of Supabase). That meant real data — a saved tweet swipe file, edited
-- knowledge-base pages, daily routine journal entries — could be lost by
-- clearing the browser, and none of it synced across devices or had any
-- history.
--
-- This migration adds:
--   1. evening_reviews      — tomorrow's MIT + whether the evening routine
--                              was completed, one row per day.
--   2. daily_checklist_completions — generic per-day checklist completions,
--                              shared by the Physical, Instagram, and X
--                              "Daily Workflow" checklists (checklist_key
--                              distinguishes them).
--   3. tweet_models         — the X page's saved tweet swipe file (was
--                              flowstate_tweet_models, localStorage only).
--   4. etsy_kb_overrides    — Tom's edited versions of the Etsy Knowledge
--                              Base pages (was flowstate_etsy_kb_*).
--   5. error_log            — the morning page's "what went wrong" journal
--                              (was flowstate_error_log), so it can actually
--                              be reviewed for patterns over time.
--
-- RUN IN SUPABASE SQL EDITOR — safe to re-run
-- =============================================================

create table if not exists evening_reviews (
  review_date date primary key,
  mit text,
  completed_at timestamptz
);

alter table evening_reviews enable row level security;
drop policy if exists allow_all_evening_reviews on evening_reviews;
create policy allow_all_evening_reviews on evening_reviews for all using (true) with check (true);

create table if not exists daily_checklist_completions (
  id uuid primary key default gen_random_uuid(),
  checklist_key text not null,
  item_id text not null,
  completed_date date not null,
  completed_at timestamptz not null default now(),
  unique (checklist_key, item_id, completed_date)
);

create index if not exists daily_checklist_completions_lookup_idx
  on daily_checklist_completions (checklist_key, completed_date);

alter table daily_checklist_completions enable row level security;
drop policy if exists allow_all_daily_checklist_completions on daily_checklist_completions;
create policy allow_all_daily_checklist_completions on daily_checklist_completions for all using (true) with check (true);

create table if not exists tweet_models (
  id text primary key,
  source text not null default 'manual',
  tweet_url text,
  added_at date not null default current_date,
  author_handle text,
  author_name text,
  tweet_text text not null,
  likes integer,
  retweets integer,
  follower_estimate integer,
  engagement_ratio numeric,
  category text,
  hook_pattern text,
  format_type text,
  why_it_worked text,
  sound_money_alternative text,
  created_at timestamptz not null default now()
);

alter table tweet_models enable row level security;
drop policy if exists allow_all_tweet_models on tweet_models;
create policy allow_all_tweet_models on tweet_models for all using (true) with check (true);

create table if not exists etsy_kb_overrides (
  page_id text primary key,
  content text not null,
  updated_at timestamptz not null default now()
);

alter table etsy_kb_overrides enable row level security;
drop policy if exists allow_all_etsy_kb_overrides on etsy_kb_overrides;
create policy allow_all_etsy_kb_overrides on etsy_kb_overrides for all using (true) with check (true);

create table if not exists error_log (
  id uuid primary key default gen_random_uuid(),
  log_date date not null,
  entry_text text not null,
  created_at timestamptz not null default now()
);

create index if not exists error_log_date_idx on error_log (log_date);

alter table error_log enable row level security;
drop policy if exists allow_all_error_log on error_log;
create policy allow_all_error_log on error_log for all using (true) with check (true);

-- =============================================================
-- ---- migrations/024_page_visits.sql ----
-- =============================================================
-- =============================================================
-- FlowState — track page visits in the database
--
-- The Home page shows a warning badge on each section pill once it's been
-- a few days since you last opened it. That was driven entirely by
-- flowstate_last_visit_<route> in localStorage, so it only ever reflected
-- activity on one browser — a fresh browser or a cleared cache made every
-- pill look stale even if you visit constantly elsewhere.
--
-- This migration adds a single table so "last visited" is a real,
-- cross-device fact instead of a per-browser guess.
--
-- RUN IN SUPABASE SQL EDITOR — safe to re-run
-- =============================================================

create table if not exists page_visits (
  route text primary key,
  last_visited_at timestamptz not null default now()
);

alter table page_visits enable row level security;
drop policy if exists allow_all_page_visits on page_visits;
create policy allow_all_page_visits on page_visits for all using (true) with check (true);

-- =============================================================
-- ---- migrations/025_fix_missing_rls.sql ----
-- =============================================================
-- =============================================================
-- FlowState — fix missing RLS policies on the tables added in
-- 022_morning_routine.sql, 023_localstorage_to_db.sql, and 024_page_visits.sql
--
-- Every other table-creating migration in this project explicitly runs:
--   alter table X enable row level security;
--   create policy allow_all_X on X for all using (true) with check (true);
-- Those three migrations missed that step. The likely effect: SELECT still
-- worked (default grants), which is why pages loaded and showed data with
-- no error banner — but INSERT/UPDATE/DELETE through the anon key were
-- silently rejected, so nothing written from the app (routine completions,
-- evening reviews, checklist ticks, tweet models, KB edits, error log
-- entries, page visits) ever actually reached the database. This is almost
-- certainly why page_visits stayed empty after clicking pills, and may also
-- explain why morning routine completions and the other new features looked
-- like they saved but didn't persist across reloads.
--
-- RUN IN SUPABASE SQL EDITOR — safe to re-run
-- =============================================================

alter table morning_routine_items enable row level security;
drop policy if exists allow_all_morning_routine_items on morning_routine_items;
create policy allow_all_morning_routine_items on morning_routine_items for all using (true) with check (true);

alter table morning_routine_completions enable row level security;
drop policy if exists allow_all_morning_routine_completions on morning_routine_completions;
create policy allow_all_morning_routine_completions on morning_routine_completions for all using (true) with check (true);

alter table evening_reviews enable row level security;
drop policy if exists allow_all_evening_reviews on evening_reviews;
create policy allow_all_evening_reviews on evening_reviews for all using (true) with check (true);

alter table daily_checklist_completions enable row level security;
drop policy if exists allow_all_daily_checklist_completions on daily_checklist_completions;
create policy allow_all_daily_checklist_completions on daily_checklist_completions for all using (true) with check (true);

alter table tweet_models enable row level security;
drop policy if exists allow_all_tweet_models on tweet_models;
create policy allow_all_tweet_models on tweet_models for all using (true) with check (true);

alter table etsy_kb_overrides enable row level security;
drop policy if exists allow_all_etsy_kb_overrides on etsy_kb_overrides;
create policy allow_all_etsy_kb_overrides on etsy_kb_overrides for all using (true) with check (true);

alter table error_log enable row level security;
drop policy if exists allow_all_error_log on error_log;
create policy allow_all_error_log on error_log for all using (true) with check (true);

alter table page_visits enable row level security;
drop policy if exists allow_all_page_visits on page_visits;
create policy allow_all_page_visits on page_visits for all using (true) with check (true);

-- =============================================================
-- ---- migrations/026_mobility_program.sql ----
-- =============================================================
-- 026_mobility_program.sql
-- Squat & Snatch Mobility Program: a rotating knee/ankle/lower-back/hip
-- bodyweight program, aimed at eventually hitting a full deep squat and a
-- snatch lift. The exercise pool and weekly rotation logic live in
-- lib/mobility.ts (client-side, deterministic) — this migration only adds:
--   1. mobility_program — single row storing when the 4-week cycle started
--   2. A morning_routine_items row (mr-mobility) so today's mobility work
--      shows up as one step in the morning routine
--   3. A daily reminders row so it also shows on every Calendar day
-- Per-exercise tick-off reuses the existing generic
-- daily_checklist_completions table (checklist_key = 'mobility'), no new
-- table needed for that.

create table if not exists mobility_program (
  id         text primary key default 'default',
  start_date date not null default current_date
);

alter table mobility_program enable row level security;
drop policy if exists allow_all_mobility_program on mobility_program;
create policy allow_all_mobility_program on mobility_program for all using (true) with check (true);

insert into mobility_program (id, start_date)
values ('default', current_date)
on conflict (id) do nothing;

-- Insert the morning routine step, shifting anything from the ankle-mobility
-- item onward down by one slot so it lands right after it (only runs once —
-- guarded so re-running this migration doesn't keep shifting sort order).
do $$
begin
  if not exists (select 1 from morning_routine_items where id = 'mr-mobility') then
    update morning_routine_items set sort_order = sort_order + 1 where sort_order >= 6;
    insert into morning_routine_items (id, title, minutes, note, category, sort_order)
    values ('mr-mobility', 'Mobility Program — today''s focus', 6, null, 'Movement', 6);
  end if;
end $$;

insert into reminders (id, title, emoji, color, start_date, recurrence, time_label)
values (
  'mobility-program',
  'Mobility Program',
  '🦵',
  '#8b5cf6',
  current_date::text,
  '{"type":"daily"}',
  'Anytime'
)
on conflict (id) do nothing;

-- =============================================================
-- ---- migrations/027_task_time_blocks.sql ----
-- =============================================================
-- 027_task_time_blocks.sql
-- Adds optional time-of-day scheduling to master_tasks so the Calendar's
-- Timeline view can place tasks on an hourly grid and let the user
-- drag-move / drag-resize them, instead of only sorting by section.
-- Both columns are nullable: a task with no start_time falls back to the
-- Timeline view's default placement (Flow -> morning window, Personal/Admin
-- -> evening window) computed client-side, so nothing has to backfill.

alter table master_tasks add column if not exists start_time text;   -- 'HH:MM' 24h, e.g. '09:30'
alter table master_tasks add column if not exists duration_min integer; -- minutes, e.g. 30

comment on column master_tasks.start_time is 'Optional HH:MM (24h) time-of-day for the Calendar Timeline view. Null = auto-placed by task_type.';
comment on column master_tasks.duration_min is 'Optional block length in minutes for the Calendar Timeline view. Null = default (30).';

-- =============================================================
-- ---- migrations/028_weekly_targets.sql ----
-- =============================================================
-- ============================================================
-- 028_weekly_targets.sql  —  Weekly output targets (home page)
-- ============================================================
-- weekly_targets: the definitions ("3 Shorts", "1 Long-form", ...).
-- tracking = 'auto_shorts' | 'auto_longform' | 'manual'
--   auto_* targets are counted live from content_items (pipeline_stage =
--   Live, updated this week) rather than stored — nothing to keep in sync.
--   manual targets are ticked up/down by hand and stored per week below.

create table if not exists weekly_targets (
  id            uuid        primary key default gen_random_uuid(),
  label         text        not null,
  emoji         text        not null default '#',
  color         text        not null default '#00d4ff',
  target_count  integer     not null default 1,
  tracking      text        not null default 'manual', -- auto_shorts | auto_longform | manual
  sort_order    integer     not null default 0,
  active        boolean     not null default true,
  created_at    timestamptz not null default now()
);

-- weekly_target_progress: manual tally per target per week (Monday date).
create table if not exists weekly_target_progress (
  id            uuid        primary key default gen_random_uuid(),
  target_id     uuid        not null references weekly_targets(id) on delete cascade,
  week_start    date        not null,
  manual_count  integer     not null default 0,
  updated_at    timestamptz not null default now(),
  unique(target_id, week_start)
);

create index if not exists weekly_target_progress_week_idx on weekly_target_progress(week_start);

alter table weekly_targets          enable row level security;
alter table weekly_target_progress  enable row level security;

drop policy if exists allow_all_weekly_targets          on weekly_targets;
drop policy if exists allow_all_weekly_target_progress  on weekly_target_progress;

create policy allow_all_weekly_targets         on weekly_targets         for all using (true) with check (true);
create policy allow_all_weekly_target_progress on weekly_target_progress for all using (true) with check (true);

-- ---- Seed: default weekly targets ----
insert into weekly_targets (label, emoji, color, target_count, tracking, sort_order) values
  ('Shorts',         '🎬', '#ff4466', 3, 'auto_shorts',    0),
  ('Long-form',      '🎥', '#00d4ff', 1, 'auto_longform',  1),
  ('Etsy listings',  '🛍',  '#f97316', 4, 'manual',         2),
  ('Website work',   '💻', '#8b5cf6', 1, 'manual',         3)
on conflict do nothing;

-- =============================================================
-- ---- migrations/029_weekly_target_picks.sql ----
-- =============================================================
-- ============================================================
-- 029_weekly_target_picks.sql — "This week's" long-form / short pick
-- ============================================================
-- Companion to weekly_targets (028). The Shorts/Long-form targets already
-- auto-count how many videos of each format hit Live this week — this table
-- adds the ability to SELECT which specific pipeline item you're actually
-- committing to ship as this week's long-form / short-form piece, chosen
-- from the Content page. The home page then shows that title alongside the
-- auto-counted progress instead of just a bare number.
--
-- One pick per (target, week) — re-picking overwrites the prior choice via
-- the unique constraint + upsert. content_item_id is nullable and ON DELETE
-- SET NULL so removing the underlying video doesn't break the row.

create table if not exists weekly_target_picks (
  id              uuid        primary key default gen_random_uuid(),
  target_id       uuid        not null references weekly_targets(id) on delete cascade,
  week_start      date        not null,
  content_item_id uuid        references content_items(id) on delete set null,
  updated_at      timestamptz not null default now(),
  unique(target_id, week_start)
);

create index if not exists weekly_target_picks_week_idx on weekly_target_picks(week_start);

alter table weekly_target_picks enable row level security;
drop policy if exists allow_all_weekly_target_picks on weekly_target_picks;
create policy allow_all_weekly_target_picks on weekly_target_picks for all using (true) with check (true);

-- =============================================================
-- ---- migrations/030_weekly_exercise_plan.sql ----
-- =============================================================
-- ============================================================
-- 030_weekly_exercise_plan.sql — Physical page weekly organiser
-- ============================================================
-- Lets the user assign exercises to specific days of the week from the
-- Physical page (a recurring template, not tied to a specific calendar
-- week — day_of_week repeats every week until changed). The home page
-- reads this table filtered to today's day_of_week and shows "Today's
-- physical" as a real checklist, so planning and daily execution share
-- one source of truth.
--
-- day_of_week matches JS Date.getDay(): 0 = Sunday .. 6 = Saturday.
-- Completion state is tracked separately via the existing
-- daily_checklist_completions table (checklist_key = 'physical_plan',
-- item_id = this row's id, completed_date = today) — no new tracking
-- table needed, and it resets automatically each day.

create table if not exists weekly_exercise_plan (
  id          uuid        primary key default gen_random_uuid(),
  day_of_week int         not null check (day_of_week between 0 and 6),
  label       text        not null,
  category    text,
  sort_order  int         not null default 0,
  created_at  timestamptz not null default now()
);

create index if not exists weekly_exercise_plan_day_idx on weekly_exercise_plan(day_of_week);

alter table weekly_exercise_plan enable row level security;
drop policy if exists allow_all_weekly_exercise_plan on weekly_exercise_plan;
create policy allow_all_weekly_exercise_plan on weekly_exercise_plan for all using (true) with check (true);

-- =============================================================
-- ---- migrations/031_ensure_rls_all_tables.sql ----
-- =============================================================
-- 031_ensure_rls_all_tables.sql
-- =============================================================
-- FlowState is single-user, accessed only via the anon key, so every
-- table needs RLS enabled + a permissive "allow_all" policy or reads/
-- writes silently fail (or, per 025_fix_missing_rls.sql's finding,
-- reads can appear to work via default grants while writes are
-- rejected). Migrations have added tables one at a time and a few have
-- been missed over time (025 already caught three of them).
--
-- This migration is a one-shot sweep across every table this project
-- has ever created, idempotent and safe to re-run: it (re)creates the
-- same "allow_all" policy already used everywhere else in this repo
-- for any table that's missing it, and leaves already-correct tables
-- untouched.
--
-- RUN IN SUPABASE SQL EDITOR -- safe to re-run
-- =============================================================

do $$
declare
  t text;
  all_tables text[] := array[
    'habits', 'habit_completions',
    'vault_items',
    'daily_tasks', 'daily_intentions', 'routine_completions',
    'content_items',
    'tasks',
    'projects',
    'master_tasks',
    'personal_items', 'goals',
    'workspace_links',
    'reminders', 'habit_blocks', 'checklist_state', 'welsh_progress', 'welsh_custom_words',
    'priority_lists',
    'site_ideas',
    'content_step_completions',
    'morning_routine_items', 'morning_routine_completions',
    'daily_plans', 'daily_plan_settings', 'content_stage_notes', 'x_ideas',
    'evening_reviews', 'daily_checklist_completions', 'tweet_models', 'etsy_kb_overrides', 'error_log',
    'mobility_program',
    'weekly_targets', 'weekly_target_progress',
    'weekly_target_picks',
    'weekly_exercise_plan',
    'page_visits'
  ];
begin
  foreach t in array all_tables
  loop
    if to_regclass(t) is not null then
      execute format('alter table %I enable row level security;', t);
      execute format('drop policy if exists allow_all_%s on %I;', t, t);
      execute format('create policy allow_all_%s on %I for all using (true) with check (true);', t, t);
    end if;
  end loop;
end $$;

-- =============================================================
-- ---- migrations/032_add_reverse_plank.sql ----
-- =============================================================
-- =============================================================
-- FlowState — add "Reverse plank hold" to the morning routine
--
-- morning_routine_items is a runtime-editable table (see
-- 022_morning_routine.sql) -- this migration just seeds one more row so
-- it shows up without hand-adding it in the app. Idempotent: appended
-- with a fresh id and guarded by ON CONFLICT DO NOTHING, same as the
-- original seed, so re-running this (or RUN_ALL.sql) is always safe.
--
-- RUN IN SUPABASE SQL EDITOR -- safe to re-run
-- =============================================================

insert into morning_routine_items (id, title, minutes, note, category, sort_order) values
  ('mr-revplank', 'Reverse plank hold', 2, '2 minute hold -- hips up, glutes squeezed, shoulders back', 'Movement', 12)
on conflict (id) do nothing;

-- =============================================================
-- ---- migrations/033_yt_channel_audit.sql ----
-- =============================================================
-- 033_yt_channel_audit.sql
-- YouTube Channel Audit: recurring reminder so the new "Channel Audit" tab
-- on app/youtube/page.tsx (checklist_state key 'yt_audit') gets re-run
-- monthly. Checklist items/state live entirely in the app (checklist_state,
-- migration 012) -- this migration only adds the Calendar-side nudge.

insert into reminders (id, title, emoji, color, start_date, recurrence, time_label)
values (
  'yt-channel-audit',
  'YouTube Channel Audit',
  '📺',
  '#8b5cf6',
  current_date::text,
  '{"type":"monthly","every":1}',
  'Anytime'
)
on conflict (id) do nothing;

-- =============================================================
-- ---- migrations/034_meme_library_refresh_reminder.sql ----
-- =============================================================
-- 034_meme_library_refresh_reminder.sql
-- Meme library (lib/memes.ts, YouTube page "Memes" tab) is a Claude-synced
-- snapshot of the "Sound Money Memes" Drive folder, not a live connection --
-- it only updates when Tom asks Claude to "refresh the meme library". This
-- reminder is the nudge to actually do that periodically. Monthly by
-- default; edit the recurrence on the Calendar > Reminders tab like any
-- other reminder if a different cadence fits better.

insert into reminders (id, title, emoji, color, start_date, recurrence, time_label)
values (
  'meme-library-refresh',
  'Refresh the meme library (tell Claude to re-sync Sound Money Memes)',
  '🖼️',
  '#00d4ff',
  current_date::text,
  '{"type":"monthly","every":1}',
  'Anytime'
)
on conflict (id) do nothing;

-- =============================================================
-- ---- migrations/035_content_focus_sessions.sql ----
-- =============================================================
-- ============================================================
-- 035_content_focus_sessions.sql — Chunked focus session logging
-- Content Pipeline items get worked in small 3-4 task chunks sized to a
-- ~60 minute budget (see lib/sops.ts nextSessionChunk / SESSION_TIME_BUDGET_MINS).
-- Nothing previously persisted that a session ever happened at all --
-- content_step_completions (018_content_focus.sql) tracks which checklist
-- steps are ticked, but not when a focus sitting started/ended or how many
-- there were. This table is purely additive, for the "how many focus
-- sessions did I do today, how much progress" view on the Home page.
-- ============================================================

create table if not exists content_focus_sessions (
  id                uuid        primary key default gen_random_uuid(),
  content_item_id   uuid        not null references content_items(id) on delete cascade,
  sop_id            text        not null,        -- matches SOP.id in lib/sops.ts
  step_indices      jsonb       not null default '[]'::jsonb,  -- which steps this chunk covered
  estimated_mins    int         not null default 0,
  actual_mins       int,                          -- set on completion/exit
  tasks_completed   int         not null default 0,
  status            text        not null default 'in_progress', -- 'in_progress' | 'completed' | 'abandoned'
  started_at        timestamptz not null default now(),
  ended_at          timestamptz
);

create index if not exists content_focus_sessions_item_idx on content_focus_sessions(content_item_id);
create index if not exists content_focus_sessions_started_idx on content_focus_sessions(started_at);

alter table content_focus_sessions enable row level security;
drop policy if exists allow_all_content_focus_sessions on content_focus_sessions;
create policy allow_all_content_focus_sessions on content_focus_sessions for all using (true) with check (true);

-- =============================================================
-- ---- migrations/036_dedupe_habits.sql ----
-- =============================================================
-- 036_dedupe_habits.sql — Fix duplicate habits, make it structurally
-- impossible to happen again.
--
-- Root cause: 006_habits.sql's seed insert used "on conflict do nothing"
-- but the habits table had no unique constraint for anything to actually
-- conflict on (id is a fresh random uuid every time) -- so every time the
-- seed insert ran again (e.g. re-running RUN_ALL.sql against an already-
-- provisioned database), it silently added another full set of duplicate
-- habit rows instead of being skipped. That's why the Tracking page and
-- Home's streaks row started showing repeated habits, and why finishing
-- the Morning Routine stopped extending its Habit Tracker streak --
-- completeMorningRoutineHabit() (lib/supabase.ts) and Home's own
-- cross-check both looked the habit up by title with .maybeSingle(),
-- which errors out the moment more than one row shares that title, and
-- that error was never surfaced anywhere, so it just silently no-op'd.
--
-- This migration is idempotent and safe to re-run: for each set of
-- same-titled habit rows it keeps the oldest one, moves any completions
-- recorded against the newer duplicates onto it, deletes the duplicates,
-- then adds a real unique constraint on title so this can't recur. Once
-- re-run with no duplicates left, both statements below simply affect 0
-- rows and the CREATE UNIQUE INDEX is a no-op.

with ranked as (
  select id, title,
         first_value(id) over (partition by title order by created_at asc, id asc) as keeper_id
  from habits
),
dups as (
  select id, keeper_id from ranked where id <> keeper_id
)
insert into habit_completions (habit_id, completed_date)
select d.keeper_id, hc.completed_date
from habit_completions hc
join dups d on d.id = hc.habit_id
on conflict (habit_id, completed_date) do nothing;

with ranked as (
  select id, title,
         first_value(id) over (partition by title order by created_at asc, id asc) as keeper_id
  from habits
)
delete from habits where id in (select id from ranked where id <> keeper_id);

create unique index if not exists habits_title_unique_idx on habits(title);

-- =============================================================
-- ---- migrations/037_dedupe_weekly_targets.sql ----
-- =============================================================
-- 037_dedupe_weekly_targets.sql — Same bug as 036_dedupe_habits.sql, same
-- fix, different table. 028_weekly_targets.sql's seed insert already used
-- a bare "on conflict do nothing", but weekly_targets never had a unique
-- constraint on label -- so re-running RUN_ALL.sql kept silently adding
-- another full set of the 4 default targets. That's the "lots of empty
-- boxes" on Home's This week's targets section.

with ranked as (
  select id, label,
         first_value(id) over (partition by label order by created_at asc, id asc) as keeper_id
  from weekly_targets
),
dups as (
  select id, keeper_id from ranked where id <> keeper_id
)
insert into weekly_target_progress (target_id, week_start, manual_count, updated_at)
select d.keeper_id, wtp.week_start, wtp.manual_count, wtp.updated_at
from weekly_target_progress wtp
join dups d on d.id = wtp.target_id
on conflict (target_id, week_start) do nothing;

with ranked as (
  select id, label,
         first_value(id) over (partition by label order by created_at asc, id asc) as keeper_id
  from weekly_targets
),
dups as (
  select id, keeper_id from ranked where id <> keeper_id
)
insert into weekly_target_picks (target_id, week_start, content_item_id, updated_at)
select d.keeper_id, wtp.week_start, wtp.content_item_id, wtp.updated_at
from weekly_target_picks wtp
join dups d on d.id = wtp.target_id
on conflict (target_id, week_start) do nothing;

with ranked as (
  select id, label,
         first_value(id) over (partition by label order by created_at asc, id asc) as keeper_id
  from weekly_targets
)
delete from weekly_targets where id in (select id from ranked where id <> keeper_id);

create unique index if not exists weekly_targets_label_unique_idx on weekly_targets(label);

-- ---- migrations/038_yap_session_and_storyboard.sql ----
-- =============================================================
-- FlowState — Yap Session transcripts + Storyboard blocks
--
-- Two new per-content-item tables supporting the Scripting stage:
--
-- 1. content_yap_transcripts — one row per content item, holding the whole
--    back-and-forth "yap session" conversation (you talk out loud about the
--    video, Claude interviews you with follow-ups) as a JSON array of
--    {role, content} messages. Single row per item (primary key on
--    content_item_id) since there's only ever one running conversation per
--    video, updated in place rather than accumulating history rows.
--
-- 2. content_storyboard_blocks — many rows per content item, one per shot/
--    beat: the spoken line plus what's on screen at that moment (b-roll,
--    screenshot, animation, image, meme, text overlay, SFX, or just VO).
--    Ordered by sort_order. This is the color-coded script — reading down
--    the list is the storyboard, and counting rows by asset_type is the
--    asset checklist ("collect 4 b-roll clips, 3 screenshots...") before
--    you ever open Premiere.
--
-- RUN IN SUPABASE SQL EDITOR — safe to re-run
-- =============================================================

create table if not exists content_yap_transcripts (
  content_item_id uuid primary key references content_items(id) on delete cascade,
  messages jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table content_yap_transcripts enable row level security;
drop policy if exists allow_all_content_yap_transcripts on content_yap_transcripts;
create policy allow_all_content_yap_transcripts on content_yap_transcripts for all using (true) with check (true);

create table if not exists content_storyboard_blocks (
  id uuid primary key default gen_random_uuid(),
  content_item_id uuid not null references content_items(id) on delete cascade,
  sort_order integer not null default 0,
  text text not null default '',
  -- 'vo' | 'text' | 'broll' | 'screenshot' | 'animation' | 'image' | 'meme' | 'sfx'
  asset_type text not null default 'vo',
  note text,
  created_at timestamptz not null default now()
);

create index if not exists content_storyboard_blocks_item_idx on content_storyboard_blocks(content_item_id, sort_order);

alter table content_storyboard_blocks enable row level security;
drop policy if exists allow_all_content_storyboard_blocks on content_storyboard_blocks;
create policy allow_all_content_storyboard_blocks on content_storyboard_blocks for all using (true) with check (true);
-- ---- migrations/039_content_focus_settings.sql ----
-- =============================================================
-- FlowState — Configurable focus-star cap
--
-- content_focus_settings — single-row config (same singleton pattern as
-- daily_plan_settings in 020_daily_plan_and_stage_notes.sql) holding how
-- many content_items can be pinned (is_active_focus = true) at once in the
-- YouTube Content Pipeline. Was hardcoded to 2 everywhere; Tom wants to set
-- it himself instead.
--
-- RUN IN SUPABASE SQL EDITOR — safe to re-run
-- =============================================================

create table if not exists content_focus_settings (
  id              int primary key default 1,
  max_focus_items int not null default 2,
  updated_at      timestamptz not null default now(),
  constraint content_focus_settings_singleton check (id = 1)
);

insert into content_focus_settings (id) values (1) on conflict (id) do nothing;

alter table content_focus_settings enable row level security;
drop policy if exists allow_all_content_focus_settings on content_focus_settings;
create policy allow_all_content_focus_settings on content_focus_settings for all using (true) with check (true);

-- ---- migrations/040_drive_integration.sql ----
-- =============================================================
-- FlowState — Google Drive integration (SOUND MONEY HQ)
--
-- drive_folder_map — single-row config (same singleton pattern as
-- daily_plan_settings / content_focus_settings) pointing at the key
-- subfolders inside Tom's "SOUND MONEY HQ" Drive folder
-- (admin@derivativemedia.co.uk). Pre-filled with the real folder IDs
-- discovered when this was set up (30 Aug 2026) so no manual entry is
-- needed — editable later from Settings if the structure ever changes.
--
-- content_items gains drive_folder_id (the raw Drive id, for future API
-- calls) alongside the existing drive_url column (022_video_links_and_stats.sql
-- — "the video's asset folder in Google Drive", already wired into the
-- Pipeline card's Assets chip and Full History) which the auto-create action
-- below writes the link into, rather than adding a second, duplicate link
-- field.
--
-- RUN IN SUPABASE SQL EDITOR — safe to re-run
-- =============================================================

create table if not exists drive_folder_map (
  id                              int primary key default 1,
  root_folder_id                  text,   -- SOUND MONEY HQ
  brand_folder_id                 text,   -- 01_BRAND (Logos, Fonts, Colors, Brand Guidelines)
  asset_library_folder_id         text,   -- 02_ASSET_LIBRARY (topic-organised b-roll/graphics)
  premiere_templates_folder_id    text,   -- 04_PREMIERE (Master_Longform_Template, Master_Short_Template)
  projects_longform_folder_id     text,   -- 07_PROJECTS/LONGFORM
  projects_shorts_folder_id       text,   -- 07_PROJECTS/SHORTS
  project_template_folder_id      text,   -- 07_PROJECTS/TEMPLATE_TO_COPY_001_XXX (subfolder skeleton to replicate per video)
  updated_at                      timestamptz not null default now(),
  constraint drive_folder_map_singleton check (id = 1)
);

insert into drive_folder_map (
  id, root_folder_id, brand_folder_id, asset_library_folder_id,
  premiere_templates_folder_id, projects_longform_folder_id,
  projects_shorts_folder_id, project_template_folder_id
) values (
  1,
  '1yIJQWkH92M9lxVFNmdCkwnOPuA8pHqcV',
  '1fh_RT7dSDCDRKfD5MYj73RXTH0k1_CFA',
  '1Ztro3pSoFuiDm_gFPSYBwraPxKVtjnSe',
  '1Yi8nK78BGZR4FJZI4KUaWbaUr9OvsEk2',
  '1-moPSyof2ieq_L6vA-wJo2wR_6nR30Cg',
  '1U7xwkwBAztbToHCkpWOuljhKBS-iTI0W',
  '1RE3tnR8dxkzSJRxEzdkeBpnzMQxlAngD'
)
on conflict (id) do nothing;

alter table drive_folder_map enable row level security;
drop policy if exists allow_all_drive_folder_map on drive_folder_map;
create policy allow_all_drive_folder_map on drive_folder_map for all using (true) with check (true);

alter table content_items add column if not exists drive_folder_id text;
-- ---- migrations/041_reminder_habit_duration.sql ----
-- =============================================================
-- FlowState — Reminder/Habit duration on the Calendar Timeline
--
-- reminders and habit_blocks only ever had a single free-text time_label
-- ("9am", "18:00") and a hardcoded 30-minute block on the Timeline — there
-- was no way to drag-resize their end time or set one in the edit modal,
-- unlike tasks (which have start_time + duration_min). Adds duration_min to
-- both tables, defaulting to 30 so existing rows render exactly as before
-- until Tom actually resizes one.
--
-- RUN IN SUPABASE SQL EDITOR — safe to re-run
-- =============================================================

alter table reminders add column if not exists duration_min integer not null default 30;
alter table habit_blocks add column if not exists duration_min integer not null default 30;
-- ---- migrations/042_channel_watchlist_and_adobe_skills.sql ----
-- =============================================================
-- FlowState — Channel watchlist (Content Pipeline > Ideas) + Adobe Skills
--
-- channel_watchlist — YouTube channels in Tom's niche or a similar/adjacent
-- niche worth keeping an eye on, added from the Ideas Bank tab of the
-- Content Pipeline (app/content/page.tsx).
--
-- adobe_skill_resources — a running library of Premiere Pro / After Effects
-- / Illustrator learning resources: a website or YouTube video Tom names and
-- describes, with a simple to-learn/learned tracker. New dedicated section,
-- app/adobe-skills/page.tsx.
--
-- RUN IN SUPABASE SQL EDITOR — safe to re-run
-- =============================================================

create table if not exists channel_watchlist (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  url         text not null,
  niche       text,
  notes       text,
  created_at  timestamptz not null default now()
);

alter table channel_watchlist enable row level security;
drop policy if exists allow_all_channel_watchlist on channel_watchlist;
create policy allow_all_channel_watchlist on channel_watchlist for all using (true) with check (true);

create table if not exists adobe_skill_resources (
  id          uuid primary key default gen_random_uuid(),
  tool        text not null default 'General',
  title       text not null,
  url         text not null,
  description text,
  status      text not null default 'To learn',
  created_at  timestamptz not null default now()
);

alter table adobe_skill_resources enable row level security;
drop policy if exists allow_all_adobe_skill_resources on adobe_skill_resources;
create policy allow_all_adobe_skill_resources on adobe_skill_resources for all using (true) with check (true);
